# Generated by Django 5.2.1 on 2025-05-14 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('rpg', 'RPG'), ('fps', 'FPS'), ('strategy', 'Stratégie'), ('platformer', 'Plateformes'), ('adventure', 'Aventure'), ('simulation', 'Simulation'), ('puzzle', 'Puzzle'), ('metroidvania', 'Metroidvania'), ('visual_novel', 'Visual Novel'), ('other', 'Autre')], max_length=20)),
                ('ambiance', models.CharField(choices=[('post_apo', 'Post-apocalyptique'), ('cyberpunk', 'Cyberpunk'), ('fantasy', 'Fantasy'), ('medieval', 'Médiéval'), ('sci_fi', 'Science-Fiction'), ('horror', 'Horreur'), ('steampunk', 'Steampunk'), ('noir', 'Noir/Detective'), ('western', 'Western'), ('dreamlike', 'Onirique'), ('other', 'Autre')], max_length=20)),
                ('keywords', models.CharField(max_length=200)),
                ('cultural_references', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('background', models.TextField()),
                ('abilities', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_description', models.TextField(blank=True)),
                ('plot', models.TextField(blank=True)),
                ('act1', models.TextField(blank=True)),
                ('act2', models.TextField(blank=True)),
                ('act3', models.TextField(blank=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='games.game')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
